version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install -g vite
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - pwd
      - ls
artifacts:
  base-directory: 'dist'
  files:
    - '**/*'